### ISSUE TITLE
Use correct memory orderings

### ISSUE THREAD

**Issue by planetis-m** [elijahr/lockfreequeues#6]
hello, first of thank you for making this! Ive noticed you use moRelaxed everywhere, this is obviously not correct, as it leads to data races. One way to test this is with [ThreadSanitizer](https://clang.llvm.org/docs/ThreadSanitizer.html), an [example](https://github.com/planetis-m/libfuzzer/blob/master/tests/ttsan.nim). An oversimplification, but a good starting point is to make all loads moAcquire and stores moRelease. Basically you need to do the publishing [protocol](https://youtu.be/ZQFzMfHIxng?t=2260). You can use moRelaxed when outside or inside a "critical section" (I think but that might also be an oversimplification), that is code between a load and a store.

**Comment by elijahr** [comment]
@planetis-m thanks so much for the bug report! I can look into this further when I have some time in the coming weeks. If you want a fix sooner a pull request would be very welcome. If I end up doing this, I would appreciate your review on the changeset. Cheers!

**Comment by planetis-m** [comment]
Here is my opinion (so take it with a grain of salt), the "how to write a correct ringbuffer" are not really worth the effort. I mean 1 lost slot, doesn't justify having twice the required capacity. They also need uints because of wrap around, but that's not an issue, it's just missing from this implementation. The [Wait-free ring buffer](https://www.boost.org/doc/libs/1_76_0/doc/html/atomic/usage_examples.html#boost_atomic.usage_examples.example_ringbuffer.implementation) the "classic" approach can be slightly [tweaked](https://github.com/rigtorp/SPSCQueue/blob/master/include/rigtorp/SPSCQueue.h) to hide that extra slot from the user and use any integer as capacity instead of powers of two. Here's a WIP nim [port](https://github.com/planetis-m/dumpster/blob/master/multithread/atomics/ring.nim). I'll be adding heap allocations, padding and alignment. Hopefully it's not much trouble adjusting to this algorithm in the future.

**Upd**: it's complete, now I will be focusing in https://github.com/rigtorp/MPMCQueue

**Comment by planetis-m** [comment]
Imo your project is worth pursuing as well, building on top of a spsc queue is a good design. so don't loose faith on it.

**Comment by elijahr** [comment]
> Imo your project is worth pursuing as well, building on top of a spsc queue is a good design. so don't loose faith on it.

Ha, don't worry, I haven't lost faith just because of a bug report :)

I've put plenty of time into this project. I don't have time at the moment to fully respond to your comments or look into this. If you have time to put together a pull request for me to review, it would certainly be appreciated.

Cheers!

**Comment by elijahr** [comment]
@planetis-m I think I'm using memory ordering as per your suggestion now in https://github.com/elijahr/lockfreequeues/pull/7

`nimble test` also now runs with LLVM thread sanitization to check for (and fail on) data races.

If you have some time and gumption, I'd certainly appreciate your review of that pull request. If not no problem, I'll just merge it sometime soon and cut a new release.

Cheers!
